import React from 'react';
import {
  Lightbulb,
  X,
  Check,
  Sparkles,
  Info
} from 'lucide-react';

export default function ClinicalHintModal({
  isOpen,
  onClose,
  hintText = "Consider what immediate, life-saving interventions are critical in a rapidly deteriorating patient with suspected anaphylaxis."
}) {
  if (!isOpen) return null;

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(15, 23, 42, 0.55)',
        backdropFilter: 'blur(6px)',
        WebkitBackdropFilter: 'blur(6px)',
        zIndex: 110,
        display: 'flex',
        alignItems: 'flex-end',
        justifyContent: 'center',
        padding: 0,
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          width: '100%',
          maxWidth: 480,
          background: '#FFFFFF',
          borderRadius: '32px 32px 0 0',
          padding: '24px 20px 36px 20px',
          boxShadow: '0 -10px 40px rgba(0, 0, 0, 0.15)',
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
          boxSizing: 'border-box',
          animation: 'slideUp 0.25s ease-out',
        }}
      >
        {/* Drag Handle */}
        <div style={{
          width: 44,
          height: 5,
          borderRadius: 99,
          background: '#CBD5E1',
          alignSelf: 'center',
          marginBottom: 4,
        }} />

        {/* Header: Lightbulb icon + Title + Close */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
            <div style={{
              width: 52,
              height: 52,
              borderRadius: '50%',
              background: 'linear-gradient(135deg, #FEF08A, #FDE047)',
              border: '2px solid #FACC15',
              boxShadow: '0 0 20px rgba(234, 179, 8, 0.4)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#B45309',
            }}>
              <Lightbulb size={28} fill="#B45309" strokeWidth={2} />
            </div>

            <div>
              <h3 style={{
                fontSize: '20px',
                fontWeight: 800,
                color: '#0F172A',
                margin: '0 0 2px 0',
              }}>
                Clinical Hint
              </h3>
              <p style={{
                fontSize: '13px',
                fontWeight: 600,
                color: '#64748B',
                margin: 0,
              }}>
                A hint to help you get closer to the diagnosis
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            style={{
              width: 36,
              height: 36,
              borderRadius: '50%',
              background: '#F1F5F9',
              border: 'none',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: '#64748B',
              cursor: 'pointer',
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* AI Powered Badge */}
        <div style={{ alignSelf: 'flex-start' }}>
          <span style={{
            background: '#FEF9C3',
            border: '1.5px solid #FDE047',
            color: '#B45309',
            fontSize: '12px',
            fontWeight: 800,
            padding: '4px 10px',
            borderRadius: 99,
            display: 'inline-flex',
            alignItems: 'center',
            gap: 5,
          }}>
            <Sparkles size={13} />
            AI Powered
          </span>
        </div>

        {/* Amber Hint Card */}
        <div style={{
          background: '#FEF9C3',
          border: '1.5px solid #FDE047',
          borderRadius: 22,
          padding: '20px 18px',
          color: '#1E293B',
          fontSize: '15px',
          fontWeight: 600,
          lineHeight: 1.55,
          boxShadow: '0 2px 6px rgba(234, 179, 8, 0.1)',
        }}>
          {hintText}
        </div>

        {/* Disclaimer */}
        <div style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: 6,
          fontSize: '12px',
          color: '#94A3B8',
          lineHeight: 1.45,
          fontStyle: 'italic',
        }}>
          <Info size={14} style={{ marginTop: 2, flexShrink: 0 }} />
          <span>
            This hint is generated by AI based on the current case status. It does not directly provide the diagnosis but aims to guide your clinical reasoning process.
          </span>
        </div>

        {/* Understood Button */}
        <button
          onClick={onClose}
          style={{
            width: '100%',
            padding: '16px',
            borderRadius: 20,
            background: 'linear-gradient(135deg, #22C55E 0%, #16A34A 100%)',
            border: '2px solid #15803D',
            boxShadow: '0 5px 0 #15803D, 0 10px 24px rgba(34, 197, 94, 0.35)',
            color: '#FFFFFF',
            fontSize: '16px',
            fontWeight: 800,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            cursor: 'pointer',
            marginTop: 4,
          }}
        >
          <Check size={20} strokeWidth={3} />
          <span>Understood</span>
        </button>
      </div>
    </div>
  );
}
